<?php
/**
 * Created by PhpStorm.
 * User: EPAG
 * Date: 02/03/2022
 * Time: 12:09
 */

namespace App\Repositories\Padagogie;


use App\Repositories\ResourceRepository;

class EvaluationRepository extends  ResourceRepository
{

        public function getFillière(array $data){
            $this->model = "class_mod_prof";
         return  $this->getByFilter($data); // TODO: Change the autogenerated stub
    }


    public function getClasses(array $data)
    {
        $this->model = 'classe';

        $getAllClasse = parent::getByFilter($data);


        return $getAllClasse->get();
    }

    public function getProf(array $data){
        $this->model = 'class_mod_prof';

            return $this->getByFilter($data)
                ->join('personnel','class_mod_prof.codeProfesseur,personnel.CodePersonnel')->
                select('personnel.NomPersonnel','personnel.PrenomPersonnel')
                -> get();
    }
}