<?php
/**
 * Created by PhpStorm.
 * User: EPAG
 * Date: 02/03/2022
 * Time: 12:09
 */

namespace App\Repositories\Padagogie;


use App\Repositories\ResourceRepository;

class EvaluationRepository extends  ResourceRepository
{

        public function getFillière(array $data){
            $this->model = "class_mod_prof";
         return  $this->getByFilter($data); // TODO: Change the autogenerated stub
    }

    public function getStudentsByCodeClass(array  $data)
    {
      return $this->getByFilter($data)->get();
    }


    public function getClasses(array $data)
    {
        $this->model = 'classe';

        $getAllClasse = parent::getByFilter($data);


        return $getAllClasse->get();
    }

    //getProf by class & fil
    public function getProf(array $data){
        $this->model = 'class_mod_prof';

            return $this->getByFilter($data)
                ->join('personnel','class_mod_prof.codeProfesseur','=','personnel.CodePersonnel')->orderBy('personnel.NomPersonnel')
                ->select('personnel.NomPersonnel','personnel.PrenomPersonnel','personnel.CodePersonnel')->get();
    }

    public function getModulesByProfAndClass(array $data){
        $this->model = 'class_mod_prof';

        /* Data egal
        get codeClass field && prof && year academic from class_mod_prof table
         * */
        return $this->getByFilter($data)
            ->join('modules','class_mod_prof.codeModule','=','modules.code_module')
            ->select('modules.code_module','modules.nom_module')->get();
    }
}