@extends('layouts.app', ['page' => __('User Profile'), 'pageSlug' => 'assiduite'])

@php
$data = false;
if (isset($getclassModuleProf)) {
    $data = true;

    //get niveau classe
}

@endphp

<script>
    document.getElementById('date').value = new Date().toDateInputValue();
</script>


@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-8">
                            <h4 class="card-title">{{ __($title) }}</h4>
                        </div>
                    </div>


                    <form method="get" action="{{ route('assiduite.create') }}" autocomplete="off">
                        <div class="card-body">
                            @csrf
                            @method('get')

                            <div class="form-row">
                                <div class="form-group{{ $errors->has('sem') ? ' has-danger' : '' }} col-md-2 mb-3 ">
                                    <label for="sem">{{ __('Semestre') }}</label>
                                    <select id="sem" name="sem"
                                        class="form-control{{ $errors->has('sem') ? ' is-invalid' : '' }}">
                                        <option value="1">1</option
                                            {{ old('sem', isset($dataRqt) && !empty($dataRqt) ? $dataRqt['sem'] : 'sem') == 1 ? 'selected' : '' }}>
                                        >
                                        <option value="2"
                                            {{ old('sem', isset($dataRqt) && !empty($dataRqt) ? $dataRqt['sem'] : 'sem') == 2 ? 'selected' : '' }}>
                                            2</option>
                                    </select>
                                    @include('alerts.feedback', ['field' => 'sem'])
                                </div>

                                <div class="form-group{{ $errors->has('date') ? ' has-danger' : '' }} col-md-2 mb-3 ">
                                    <label>{{ __('Date') }}</label>
                                    <input type="date" id="date" name="date"
                                        class="form-control{{ $errors->has('date') ? ' is-invalid' : '' }}"
                                        placeholder="{{ __('date') }}" value="<?php echo e(old('date', isset($dataRqt) && !empty($dataRqt) ? date('Y-m-d', strtotime($dataRqt['date'])) : date('Y-m-d'))); ?>">
                                    @include('alerts.feedback', ['field' => 'date'])
                                </div>

                                <div class="form-group{{ $errors->has('fil') ? ' has-danger' : '' }} col-md-2 mb-3 ">
                                    <label for="fil">{{ __('Fillière') }}</label>
                                    <select id="fil" name="fil"
                                        class="form-control{{ $errors->has('fil') ? ' is-invalid' : '' }}">
                                        @if ($data)
                                            @foreach ($getclassModuleProf as $codeFiliere)
                                                <option value="{{ $codeFiliere->codeFiliere }}"
                                                    {{ old('fil', isset($dataRqt) && !empty($dataRqt) ? $dataRqt['fil'] : $codeFiliere->codeFiliere) ==$codeFiliere->codeFiliere? 'selected': '' }}>
                                                    {{ $codeFiliere->codeFiliere }}
                                                </option>
                                            @endforeach
                                        @endif
                                    </select>

                                    @include('alerts.feedback', ['field' => 'fil'])
                                </div>

                                <div class="form-group{{ $errors->has('class') ? ' has-danger' : '' }} col-md-2 mb-3 ">
                                    <label for="cls">{{ __('Classe') }}</label>
                                    <select id="cls" name="cls"
                                        class="form-control{{ $errors->has('cls') ? ' is-invalid' : '' }}">
                                        @if ($data)
                                            @foreach ($getclassModuleProf->unique('niveauClasse') as $codeFiliere)
                                                <option value="{{ $codeFiliere->niveauClasse }}"
                                                    {{ old('cls', isset($dataRqt) && !empty($dataRqt) ? $dataRqt['cls'] : $codeFiliere->niveauClasse) ==$codeFiliere->niveauClasse? 'selected': '' }}>
                                                    {{ $codeFiliere->niveauClasse }}
                                                </option>
                                            @endforeach
                                        @endif
                                    </select>
                                    @include('alerts.feedback', ['field' => 'cls'])
                                </div>


                                <div class="form-group{{ $errors->has('grp') ? ' has-danger' : '' }} col-md-2 mb-3 ">
                                    <label for="grp">{{ __('Groupe') }}</label>
                                    <select id="grp" name="grp"
                                        class="form-control{{ $errors->has('grp') ? ' is-invalid' : '' }}">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                    </select>
                                    @include('alerts.feedback', ['field' => 'grp'])
                                </div>

                                <div class="form-group{{ $errors->has('annee') ? ' has-danger' : '' }} col-md-2 mb-3 ">
                                    <label for="annee">{{ __('Année scolaire') }}</label>
                                    <select id="annee" name="annee"
                                        class="form-control{{ $errors->has('annee') ? ' is-invalid' : '' }}">
                                        @if ($data)
                                            @foreach ($getclassModuleProf->unique('anneeScolaire') as $anneeScolaire)
                                                <option value="{{ $anneeScolaire->anneeScolaire }}"
                                                    {{ old('annee', isset($dataRqt) && !empty($dataRqt) ? $dataRqt['annee'] : $anneeScolaire->anneeScolaire) ==$anneeScolaire->anneeScolaire? 'selected': '' }}>
                                                    {{ $anneeScolaire->anneeScolaire }}
                                                </option>
                                            @endforeach
                                        @endif
                                    </select>
                                    @include('alerts.feedback', ['field' => 'annee'])
                                </div>

                                <div class="">
                                    <button type="submit" class="btn btn-fill btn-info">{{ __('Recherche') }}</button>
                                </div>


                            </div>

                    </form>


                    <form method="post" action="{{ route('assiduite.store') }}" autocomplete="off">

                        @csrf
                        @method('post')




                        <input name="cls" type="hidden"
                            value="{{ isset($dataRqt) && !empty($dataRqt) ? $dataRqt['cls'] : '' }}">
                        <input name="fil" type="hidden"
                            value="{{ isset($dataRqt) && !empty($dataRqt) ? $dataRqt['fil'] : '' }}">
                        <input name="annee" type="hidden"
                            value="{{ isset($dataRqt) && !empty($dataRqt) ? $dataRqt['annee'] : '' }}">
                        <input name="date" type="hidden"
                            value="{{ isset($dataRqt) && !empty($dataRqt) ? $dataRqt['date'] : '' }}">
                        <input name="sem" type="hidden"
                            value="{{ isset($dataRqt) && !empty($dataRqt) ? $dataRqt['sem'] : '' }}">

                        <div class="form-row">
                            <div class="form-group{{ $errors->has('seance') ? ' has-danger' : '' }} col-md-3 mb-3 ">
                                <label for="seance">{{ __('Séance') }}</label>
                                <select id="seance" name="seance"
                                    class="form-control{{ $errors->has('seance') ? ' is-invalid' : '' }}">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                </select>
                                @include('alerts.feedback', ['field' => 'seance'])
                            </div>


                            <div class="form-group{{ $errors->has('nbrHr') ? ' has-danger' : '' }} col-md-3 mb-3 ">
                                <label for="prf">{{ __('Nombre/heures') }}</label>
                                <select id="nbrHr" name="nbrHr"
                                    class="form-control{{ $errors->has('nbrHr') ? ' is-invalid' : '' }}">
                                    <option value="1">1,5</option>
                                    <option value="2">2</option>
                                </select>
                                @include('alerts.feedback', ['field' => 'nbrHr'])
                            </div>


                            <div class="form-group{{ $errors->has('prof') ? ' has-danger' : '' }} col-md-3 mb-3 ">
                                <label for="prof">{{ __('Professeur') }}</label>
                                <select id="prof" name="prof"
                                    class="form-control{{ $errors->has('prof') ? ' is-invalid' : '' }}">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                </select>
                                @include('alerts.feedback', ['field' => 'prof'])
                            </div>

                        </div>

                        <div class="col-md-12">

                            <div class="row">

                                <div class="col-8">
                                    <h4 class="card-title">{{ __('Présents') }}</h4>
                                    @include('alerts.success')
                                </div>
                                <div class="col-md-5">
                                    <div class="">
                                        <table class="table tablesorter " id="">
                                            <thead class=" text-primary">
                                                <tr>
                                                    <th scope="col">{{ __('Noms') }}</th>
                                                    <th scope="col"> </th>
                                                </tr>
                                            </thead>
                                            <tbody>

                                                @isset($prensent)

                                                    @foreach ($prensent as $etudiant)
                                                        <tr>
                                                            <td>
                                                                <label for="{{ $etudiant->code_etudiant }}">
                                                                    {{ $etudiant->Nom_etudiant }}
                                                                    {{ $etudiant->prenom_etudiant }}
                                                                </label>

                                                            </td>

                                                            <td>
                                                                <input id="{{ $etudiant->code_etudiant }}" type="checkbox"
                                                                    value="{{ $etudiant->code_etudiant }}"
                                                                    name="code_etudiant[]" id="code_etudiant">
                                                            </td>
                                                        </tr>
                                                    @endforeach
                                                @endisset

                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="col-md-2">


                                    <div class="row">
                                        <button type="submit" class="btn btn-fill btn-primary">{{ __('ABS') }}</button>
                                        <button type="submit" class="btn btn-fill btn-primary">{{ __('REC') }}</button>
                                    </div>


                                </div>
                                <div class="col-md-5">
                                    <div class="col-8">
                                        <h4 class="card-title">{{ __('Abscens') }}</h4>
                                    </div>
                                    <div class="">
                                        <table class="table tablesorter " id="">
                                            <thead class=" text-primary">
                                                <tr>
                                                    <th scope="col"> </th>
                                                    <th scope="col">{{ __('Noms') }}</th>
                                                    <th scope="col">{{ __('Justifier') }}</th>
                                                    <th scope="col">{{ __('Email') }}</th>
                                                    <th scope="col">{{ __('Sms') }}</th>
                                                </tr>
                                            </thead>
                                            <tbody>

                                                @isset($absents)
                                                    @foreach ($absents as $list)
                                                        <tr>
                                                            <td><input type="checkbox"></td>
                                                            <td>{{ $list->Nom_etudiant }}</td>
                                                            <td><input type="checkbox"></td>
                                                            <td><input type="checkbox"></td>
                                                            <td><input type="checkbox"></td>
                                                        </tr>
                                                    @endforeach

                                                @endisset


                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                            </div>

                        </div>
                </div>

                </form>
            </div>

            <div class="card-footer py-4">
                <nav class="d-flex justify-content-end" aria-label="...">

                </nav>
            </div>
        </div>
        <!-- <div class="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="card-header">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h5 class="title">{{ __('Password') }}</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <form method="post" action="{{ route('profile.password') }}" autocomplete="off">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @csrf
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @method('put')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @include('alerts.success', ['key' => 'password_status'])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="form-group{{ $errors->has('old_password') ? ' has-danger' : '' }}">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label>{{ __('Current Password') }}</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="password" name="old_password" class="form-control{{ $errors->has('old_password') ? ' is-invalid' : '' }}" placeholder="{{ __('Current Password') }}" value="" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @include('alerts.feedback', ['field' => 'old_password'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label>{{ __('New Password') }}</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="password" name="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="{{ __('New Password') }}" value="" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @include('alerts.feedback', ['field' => 'password'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="form-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label>{{ __('Confirm New Password') }}</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input type="password" name="password_confirmation" class="form-control" placeholder="{{ __('Confirm New Password') }}" value="" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="card-footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button type="submit" class="btn btn-fill btn-primary">{{ __('Change password') }}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>--!>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
    @endsection
